export enum ProcessStatus {
  NOT_PROCESSED = 'NOT_PROCESSED',

  PROCESSING = 'PROCESSING',

  PROCESSED = 'PROCESSED',

  NEED_PROCESS = 'NEED_PROCESS',

  NEED_PROCESS_NOW = 'NEED_PROCESS_NOW',

  NEED_HANDLE = 'NEED_HANDLE',

  NEED_HANDLE_NOW = 'NEED_HANDLE_NOW',

  ERROR = 'ERROR',

  DONE = 'DONE',
}
