@startuml
	!pragma syntax class
	enum StatusName {
		ONLINE, 
		OFFLINE, 
		BUSY, 
		TEMPORARILY_ABSENT 
	}
	enum DeviceType {
		MOBILE, 
		TABLE, 
		DESKTOP, 
		LAPTOP, 
		OTHER_DEVICE 
	}
	enum NotifyType {
		SYSTEM, 
		MANAGER, 
		ADMIN, 
		USER, 
		ANONYMOUS 
	}
	enum PostInType {
		GROUP, 
		USER, 
		PAGE 
	}
	enum PostType {
		SIMPLE, 
		ADVANCE, 
		FROALA 
	}
	enum FriendType {
		FRIEND, 
		BEST_FRIEND, 
		FAMILY, 
		BLOCK 
	}
	enum ProcessStatus {
		NOT_PROCESSED, 
		PROCESSING, 
		PROCESSED, 
		NEED_PROCESS, 
		NEED_PROCESS_NOW, 
		NEED_HANDLE, 
		NEED_HANDLE_NOW, 
		ERROR, 
		DONE 
	}
	enum EventType {
		DAY, 
		MONTH, 
		YEAR, 
		ONLY_ONE 
	}
	class HanhChinhVN <<Option {Paginate,Search,Filter,Dto,Service}>> {
		String name
		String slug
		String type
		String nameWithType
		String code
		String parentCode
		String path
		String pathWithType
	}
	class MasterUser <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String fullName
		String nickname
		TextBlob avatar
		TextBlob quickInfo
	}
	class UserProfile <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		TextBlob work
		TextBlob education
		TextBlob placesLived
		TextBlob contactInfo
		TextBlob webSocialLinks
		TextBlob basicInfo
		TextBlob relationshipInfo
		TextBlob family
		TextBlob detailAbout
		TextBlob lifeEvents
		TextBlob hobbies
		TextBlob featured
	}
	class AccountStatus <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		StatusName accountStatus
		Instant lastVisited
		String statusComment
	}
	AccountStatus ..> StatusName
	class Album <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String name
		String note
		TextBlob avatar
	}
	class DeviceStatus <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String deviceName
		DeviceType deviceType
		StatusName deviceStatus
		Instant lastVisited
		String statusComment
	}
	DeviceStatus ..> DeviceType
	DeviceStatus ..> StatusName
	class Event <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String title
		TextBlob avatar
		TextBlob content
		EventType type
		TextBlob description
		Instant startTime
		Instant endTime
		String tagLine
		TextBlob imageCollection
		TextBlob videoCollection
	}
	Event ..> EventType
	class Friend <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		FriendType friendType
	}
	Friend ..> FriendType
	class FollowUser <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class FollowGroup <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class FollowPage <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class FileInfo <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String nameFile
		String typeFile
		String path
		Long dataSize
	}
	class GroupPost <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String name
		TextBlob avatar
		TextBlob quickInfo
	}
	class GroupProfile <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class Image <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String name
		Integer width
		Integer height
		Float quality
		Integer size
		Long priorityIndex
		Long dataSize
	}
	class NewsFeed <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		Long priorityIndex
	}
	class Notification <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		NotifyType notifyType
		String title
		TextBlob content
	}
	Notification ..> NotifyType
	class MessageGroup <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String groupName
		TextBlob avatar
		String addBy
	}
	class MessageContent <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String senderName
		TextBlob attach
		TextBlob content
		TextBlob status
		TextBlob searchField
	}
	class PagePost <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String name
		TextBlob avatar
		TextBlob quickInfo
	}
	class PageProfile <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class Post <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		PostInType postInType
		PostType postType
		TextBlob content
		TextBlob searchField
	}
	Post ..> PostInType
	Post ..> PostType
	class PostComment <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		TextBlob content
	}
	class PostLike <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class RankUser <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		Float ratingPoints
	}
	class RankGroup <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class Video <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String name
		Integer width
		Integer height
		Float qualityImage
		Float qualityAudio
		Float quality
		Integer size
		Long priorityIndex
		Long dataSize
	}
	class VideoStream <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
	}
	class VideoLiveStreamBuffer <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		AnyBlob bufferData
	}
	class TopicInterest <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String title
		TextBlob content
	}
	class TodoList <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String title
		TextBlob content
	}
	GroupPost  "profile 0..1 " -- "group 0..1 "  GroupProfile
	PagePost  "profile 0..1 " -- "page 0..1 "  PageProfile
	VideoStream  "video 0..1 " -- "videoStream 0..1 "  Video
	Image  "fileInfo 0..1 " -- "0..1 "  FileInfo
	Video  "fileInfo 0..1 " -- "0..1 "  FileInfo
	FollowGroup  "followGroupDetails 0..* " o-- "0..1 "  GroupPost
	FollowPage  "followPageDetails 0..* " o-- "0..1 "  PagePost
	NewsFeed  "0..* " o-- "0..1 "  Post
	RankUser  "0..* " o-- "0..1 "  RankGroup
	AccountStatus  "0..1 " --o "0..* "  DeviceStatus
	GroupPost  "myPostInGroup 0..1 " --o "0..* "  Post
	PagePost  "myPostInPage 0..1 " --o "0..* "  Post
	MessageGroup  "0..1 " --o "0..* "  MessageContent
	Image  "imageProcessed 0..1 " --o "imageOriginal 0..* "  Image
	Video  "videoProcessed 0..1 " --o "videoOriginal 0..* "  Video
	Post  "comment 0..1 " --o "0..* "  PostComment
	Post  "like 0..1 " --o "0..* "  PostLike
	PostComment  "like 0..1 " --o "0..* "  PostLike
	Post  "postShareChildren 0..1 " --o "postShareParent 0..* "  Post
	PostComment  "commentReply 0..1 " --o "commentParent 0..* "  PostComment
	VideoStream  "0..1 " --o "0..* "  VideoLiveStreamBuffer
	Album  "0..* " o--o "0..* "  Image
	TopicInterest  "0..* " o--o "0..* "  Post
	TopicInterest  "0..* " o--o "0..* "  PagePost
	TopicInterest  "0..* " o--o "0..* "  GroupPost
	MasterUser  "0..1 " -- "0..1 "  User
	MasterUser  "myRank 0..1 " -- "0..1 "  RankUser
	MasterUser  "myBaseInfoCreated 0..1 " --o "createdBy 0..* "  BaseInfo
	MasterUser  "myBaseInfoModified 0..1 " --o "modifiedBy 0..* "  BaseInfo
	MasterUser  "OwnerOf 0..1 " --o "owner 0..* "  BaseInfo
	MasterUser  "0..1 " --o "0..* "  Permission
	Friend  "friendDetails 0..* " o-- "0..1 "  MasterUser
	FollowUser  "followUserDetails 0..* " o-- "0..1 "  MasterUser
	MasterUser  "0..* " o--o "0..* "  TopicInterest
	class Permission <<Option {Paginate,Search,Filter,Dto,Service}>> {
		Boolean read
		Boolean write
		Boolean share
		Boolean delete
		Boolean add
		Integer level
	}
	class BaseInfo <<Option {Paginate,Search,Filter,Dto,Service}>> {
		ProcessStatus processStatus
		String modifiedClass
		Instant createdDate
		Instant modifiedDate
		TextBlob notes
		TextBlob historyUpdate
		Boolean deleted
		Long priorityIndex
		Long countUse
	}
	BaseInfo ..> ProcessStatus
	class ClassInfo <<Option {Paginate,Search,Filter,Dto,Service}>> {
		UUID uuid
		String package
		String name
		String simpleName
	}
	MasterUser  "baseInfo 0..1 " -- "0..1 "  BaseInfo
	UserProfile  "0..1 " -- "0..1 "  BaseInfo
	AccountStatus  "0..1 " -- "0..1 "  BaseInfo
	DeviceStatus  "0..1 " -- "0..1 "  BaseInfo
	Friend  "0..1 " -- "0..1 "  BaseInfo
	FollowUser  "0..1 " -- "0..1 "  BaseInfo
	FollowGroup  "0..1 " -- "0..1 "  BaseInfo
	FollowPage  "0..1 " -- "0..1 "  BaseInfo
	FileInfo  "0..1 " -- "0..1 "  BaseInfo
	PagePost  "0..1 " -- "0..1 "  BaseInfo
	PageProfile  "0..1 " -- "0..1 "  BaseInfo
	GroupPost  "0..1 " -- "0..1 "  BaseInfo
	Post  "0..1 " -- "0..1 "  BaseInfo
	PostComment  "0..1 " -- "0..1 "  BaseInfo
	PostLike  "0..1 " -- "0..1 "  BaseInfo
	GroupProfile  "0..1 " -- "0..1 "  BaseInfo
	NewsFeed  "0..1 " -- "0..1 "  BaseInfo
	MessageGroup  "0..1 " -- "0..1 "  BaseInfo
	MessageContent  "0..1 " -- "0..1 "  BaseInfo
	RankUser  "0..1 " -- "0..1 "  BaseInfo
	RankGroup  "0..1 " -- "0..1 "  BaseInfo
	Notification  "0..1 " -- "0..1 "  BaseInfo
	Album  "0..1 " -- "0..1 "  BaseInfo
	Video  "0..1 " -- "0..1 "  BaseInfo
	Image  "0..1 " -- "0..1 "  BaseInfo
	VideoStream  "0..1 " -- "0..1 "  BaseInfo
	VideoLiveStreamBuffer  "0..1 " -- "0..1 "  BaseInfo
	TopicInterest  "0..1 " -- "0..1 "  BaseInfo
	TodoList  "0..1 " -- "0..1 "  BaseInfo
	Event  "0..1 " -- "0..1 "  BaseInfo
	Permission  "0..* " o-- "0..1 "  BaseInfo
	BaseInfo  "0..* " o-- "0..1 "  ClassInfo
	class User <<Option {Paginate,Search,Filter,Dto,Service}>> {
		String firstName
		String lastName
		String login
		String email
		String imageUrl
		String authorities
	}
@enduml

